packages:
# - 'packages/badgers'
# - 'packages/blockpoint'
# - 'packages/blocktop'
# - 'packages/catdex'
# - 'packages/common'
# - 'packages/dutch'
# - 'packages/flash'
# - 'packages/future'
# - 'packages/locktime'
# - 'packages/subscription'
# - 'packages/trust'
# - 'packages/app'
 - 'packages/*'
