packages:
 - 'packages/badgers'
 - 'packages/blockpoint'
 - 'packages/blocktop'
 - 'packages/catdex'
 - 'packages/common'
 - 'packages/drip'
 - 'packages/dutch'
 - 'packages/flash'
 - 'packages/future'
 - 'packages/locktime'
 - 'packages/small'
 - 'packages/subscription'
 - 'packages/timeout'
 - 'packages/trust'
 - 'packages/wrap'
 - 'packages/app'
# - 'packages/*'
