name: Deploy .dev

on:
  push:
    branches:
      - feature/*
      - bugfix/*
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm
      - run: pnpm app:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: vox.cash
          publish_dir: ./docs
